# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c28f6bd201bdcc9365290204d760cd4928d27a3c8495723b2e9643b55364fbe5b518adaa49ce95f0c40c2d50622cd252df824f58a99f899dcf536cbdb39b9fcc

test:
  secret_key_base: 0c1fb79980e6efd05006706155bfd2c3d0608f680d063fe96df48aa3b6eac1b360c1e3b2a6b0b786ba2965885844bd4fbcaef2f344e4d9362ae1b8310af3abfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
